export const SELL_ORDER_CREATE_REQUEST = "SELL_ORDER_CREATE_REQUEST";
export const SELL_ORDER_CREATE_SUCCESS = "SELL_ORDER_CREATE_SUCCESS";
export const SELL_ORDER_CREATE_FAIL = "SELL_ORDER_CREATE_FAIL";

export const SELL_ORDER_ADDRESS_REQUEST = "SELL_ORDER_ADDRESS_REQUEST";
export const SELL_ORDER_ADDRESS_SUCCESS = "SELL_ORDER_ADDRESS_SUCCESS";
export const SELL_ORDER_ADDRESS_FAIL = "SELL_ORDER_ADDRESS_FAIL";

